version: "3"
services:
  redis:
    container_name: redis-cache
    image: redis
    ports:
      - "6379:6379"

  db:
    container_name: postgres-db
    image: "postgres:14"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=oppari
    volumes:
      - ./pgdata:/var/lib/postgresql/data
